FROM node:18-alpine AS build

WORKDIR /app

COPY package.json ./

RUN npm cache clean -f
RUN npm install -g @angular/cli
RUN npm install -g npm
RUN npm config set fetch-retry-maxtimeout 9999999 -g
RUN npm install --registry=https://registry.npmjs.org --production=false --legacy-peer-deps --timeout=9999999

COPY . .

RUN npm run build
FROM nginx:alpine

COPY --from=build /app/dist/desaparecidos-mt-spa/browser /opt/desaparecidos-mt-spa/
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

